name: pythonci
on:
  push:
    branches:
      - master
      - main

env:
  PYTHON_VERSION: 3.x

jobs:
  pythonci:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python runtime
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          pip install .
          pip install \
            mkdocs-minify-plugin>=0.3 \
            mkdocs-redirects>=1.0 \
            mkdocs-rss-plugin>=0.17

      - name: Install Insiders build
        if: github.event.repository.fork == false
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
          mkdocs --version